### ISSUE TITLE
Should add new values to depopulated profile: JWURCDH

### ISSUE THREAD

**Issue by asarto88** [balena-io-hardware/balena-fin#90]
We should add 0ohm value for R286 and R287 to the BoM of JWURCDH depopulated profile.
See: https://app.frontapp.com/open/cnv_bw1qoel

**Comment by ntzovanis** [comment]
@asarto88 for future reference, issues regarding the balenaFin PCB should be added in this repo: https://github.com/balena-io-hardware/balena-fin-pcb-legacy/issues.

I already added this one.
